name: Regenerate json files for all add-ons

on:
  workflow_dispatch:

jobs:
  regenerateJson:
    permissions:
      contents: write
      pull-requests: write
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 3.13 ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        submodules: true
    - name: Create validation errors file
      run: echo "" > validationErrors.md
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7
    - name: Regenerate json
      run: |
        validation/regenerateJson `
        --dir ..\addons `
        --output validationErrors.md
    - name: Commit changes and open PR
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        $baseBranch = "${{ github.ref_name }}"
        $headBranch = "regenJson${{ github.run_number }}"

        git add addons
        if (git diff --staged --quiet) {
          echo "No changes to commit; skipping PR creation."
        } else {
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b $headBranch
          git commit -m "[Automated] Regenerate json files"
          git push --set-upstream origin $headBranch

          gh pr create `
            --squash `
            --base $baseBranch `
            --head $headBranch `
            --title "[Automated] Regenerate json files" `
            --body "Regenerated json files for add-ons. Triggered from workflow run ${{ github.run_id }}."
        }
    - name: Upload validation errors as artifact
      if: failure()
      uses: actions/upload-artifact@v6
      with:
        name: validationErrors
        path: validationErrors.md
