name: Check submitted NVDA add-on

on:
  pull_request:
    branches:
      - master

jobs:

  checkMetadata:
  
    name: Check metadata
  
    runs-on: windows-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.7 x86
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x86
    - name: Install dependencies
      run: pip install jsonschema
    - name: Determine changed file
      id: changedFile
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          if (context.payload.pull_request.files_changed === 1) { return }
          const diff_url = context.payload.pull_request.diff_url
          const result = await github.request(diff_url)
          return result.split(" ")[1]
          result-encoding: string
    - name: Validate metadata
      run: python _tools/validate.py ${{steps.changedFile.outputs.result}}
