name: Check submitted NVDA add-on

on:
  pull_request:
    branches:
      - master

jobs:

  checkMetadata:
  
    name: Check metadata
  
    runs-on: windows-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.7 x86
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x86
    - name: Install dependencies
      run: pip install jsonschema
    - name: View context attributes
      uses: actions/github-script@v3
      with:
        script: console.log(context.payload)