name: Check submitted NVDA add-on

on:
  pull_request:
    branches:
      - master

jobs:

  checkMetadata:
  
    name: Check metadata
  
    runs-on: windows-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up Python 3.7 x86
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x86
    - name: Install dependencies
      run: pip install jsonschema
    - name: Determine number of changed files
      id: changedFileNumber
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: return context.payload.pull_request.files_changed
    - name: Get diff
      run: |
        "if ${{steps.changedFileNumber.outputs.result}} != 1":
          print("This is not an add-on submission")
          return
        git diff -U0 origin/master...HEAD -- addons/. > pr.diff
      shell: python