name: Check submitted NVDA add-on

on:
  pull_request:
    branches:
      - master

jobs:

  checkMetadata:
  
    name: Check metadata
  
    runs-on: windows-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.7 x86
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x86
    - name: Install dependencies
      run: pip install jsonschema
    - name: 
      run: |
        import subprocess
        proc = subprocess.Popen('git diff-tree --no-commit-id --name-only -r ${{ github.sha }}', stdout=subprocess.PIPE)
        output = proc.stdout.read()
        print output
        
    - name: Validate json file
      run: python _tools\validate.py _tools\21.02.json
