name: Unit tests

on:
  pull_request:
    branches:
      - master

jobs:

  unitTests
  
    name: Unit tests
  
    runs-on: windows-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up Python 3.7 x86
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x86
    - name: Install dependencies
      run: pip install tox
    - name: Test
      run: python -m tox
